name: Copy MD Files from All Repos

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  copy-md-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'

      - name: Fetch all repositories
        run: |
          # Get all repositories for the authenticated user
          repos=$(curl -s -H "Authorization: token ${{ secrets.REPO_ACCESS_TOKEN }}" \
            https://api.github.com/user/repos?per_page=100 | jq -r '.[].full_name')

          echo "$repos" > repos.txt

      - name: Copy MD files from all repos
        run: |
          mkdir -p repos
          while IFS= read -r repo; do
            echo "Processing repository: $repo"

            # Create a directory for the repo
            repo_name=$(echo "$repo" | sed 's/\//_/g')
            repo_dir="repos/$repo_name"
            mkdir -p "$repo_dir"

            # Clone the repo
            git clone https://github.com/$repo.git temp-repo
            cd temp-repo

            # Find and copy .md files
            find . -name "*.md" -exec bash -c '
              for file; do
                if [ -f "$file" ]; then
                  # Get the file hash
                  hash=$(git hash-object "$file")
                  # Ensure the target directory exists
                  mkdir -p "$(dirname "../../$repo_dir")"
                  # Copy the file to the main repo with a new name
                  cp "$file" "../../$repo_dir/${hash}.md"
                fi
              done
            ' bash {} +

            # Clean up
            cd ..
            rm -rf temp-repo
          done < repos.txt

      - name: Commit and push changes
        run: |
          git add repos/
          git commit -m "Add .md files from all repositories"
          git push
